# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KWLazyPresentSwiftExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KWLazyPresentSwiftExample
  pod 'KWLazyPresentSwift'

end
